23102A0007 - Aarti Sakpal

In [1]:
c(2,3,5,7) + c(-2,-3,-5,8)

[1]  0  0  0 15

In [2]:
2^3

[1] 8

In [3]:
2**3

[1] 8

In [4]:
2^0.5

[1] 1.414214

In [5]:
2**0.5

[1] 1.414214

In [6]:
2^-0.5

[1] 0.7071068

In [7]:
c(2,3,5,7)^2

[1]  4  9 25 49

In [8]:
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

In [9]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

In [10]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

In [11]:
2 %/% 2

[1] 1

In [12]:
5 %/% 2

[1] 2

In [13]:
7 %/% 3

[1] 2

In [14]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

In [15]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

In [16]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

In [17]:
2 %% 2

[1] 0

In [18]:
3 %% 2

[1] 1

In [19]:
7 %% 3

[1] 1

In [20]:
7 %% 4

[1] 3

In [21]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

In [22]:
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1

In [23]:
c(2,3,5) %% c(2,3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

In [24]:
max(1.2, 3.4, -7.8)

[1] 3.4

In [25]:
max(c(1.2, 3.4, -7.8))

[1] 3.4

In [26]:
min(1.2, 3.4, -7.8)

[1] -7.8

In [27]:
min(c(1.2, 3.4, -7.8))

[1] -7.8

In [28]:
mean(2,3,4)

[1] 2

In [29]:
mean(c(2,3,4))

[1] 3

In [30]:
abs(-4)

[1] 4

In [31]:
abs(c(-1,-2,-3,4,5))

[1] 1 2 3 4 5

In [32]:
sqrt(4)

[1] 2

In [34]:
sqrt(c(4,9,16,25))

[1] 2 3 4 5

In [35]:
sum(c(2,3,5,7))

[1] 17

In [36]:
prod(c(2,3,5,7))

[1] 210

In [37]:
round(1.23)

[1] 1

In [38]:
round(1.83)

[1] 2

In [39]:
log(10)

[1] 2.302585

In [40]:
log(exp(1))

[1] 1

In [41]:
log(c(10,100,1000))

[1] 2.302585 4.605170 6.907755

In [42]:
log10(10)

[1] 1

In [43]:
log10(100)

[1] 2

In [44]:
log10(100)

[1] 2

In [45]:
log10(c(10,100,1000))

[1] 1 2 3

In [46]:
x1 = c(1,2,3,4)

In [47]:
x1

[1] 1 2 3 4

In [48]:
x2 = x1^2

In [49]:
x2

[1]  1  4  9 16

In [50]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24

In [51]:
abs( c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)) )

[1] 19 18 17 16

In [53]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8) )

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [55]:
x[3,2]

[1] 7

In [56]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = FALSE)

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [57]:
y = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = TRUE)

y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [58]:
x = matrix( nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8) )

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [59]:
dim(x)

[1] 4 2

In [60]:
nrow(x)

[1] 4

In [61]:
ncol(x)

[1] 2

In [62]:
mode(x)

[1] "numeric"

In [63]:
attributes(x)

$dim
[1] 4 2

In [65]:
help("matrix")