23102A0007 - Aarti Sakpal

In [ ]:
x = NA
x

[1] NA

In [ ]:
is.na(x)

[1] TRUE

In [ ]:
x = c(11, NA, 13, NA)
x

is.na(x)

[1] 11 NA 13 NA

[1] FALSE  TRUE FALSE  TRUE

In [ ]:
x = c(11, NA, 13, NA)

mean(x)

mean(x, na.rm = TRUE)

[1] NA

[1] 12

In [ ]:
x = NA
x

y = NULL
y

is.na(x)
is.null(x)

is.na(y)
is.null(y)

[1] NA

NULL

[1] TRUE

[1] FALSE

logical(0)

[1] TRUE

In [ ]:
x = c(11, NA, 13, NA)

x

which(is.na(x))

[1] 11 NA 13 NA

[1] 2 4

In [ ]:
x = c(11, NA, 13, NA)

x

sum(is.na(x))

[1] 11 NA 13 NA

[1] 2

In [ ]:
x = c(11, NA, 13, NA)

x

complete.cases(x)

[1] 11 NA 13 NA

[1]  TRUE FALSE  TRUE FALSE

In [ ]:
x = c(11, NA, 13, NA)

x

y = na.omit(x)

y

[1] 11 NA 13 NA

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [ ]:
x = c(11, NA, 13, NA)

y = na.omit(x)

y

mean(x)

mean(y)

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

[1] NA

[1] 12

In [ ]:
x = 5

if (x > 4) {
  x * 3
}

x = 3

if (x > 4) {
  x * 3
}

[1] 15

In [ ]:
x = 6

if (x > 3) {
  print("The value is more than 3")
}

[1] "The value is more than 3"

In [ ]:
x = 5

if (x == 3) {
  x = x - 1
} else {
  x = 2 * x
}

x

[1] 10

In [ ]:
x = 3

if (x == 3) {
  x = x - 1
} else {
  x = 2 * x
}

x

[1] 2

In [ ]:
x = 6

if (x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is more than 3"

In [ ]:
x = 2

if (x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is less than 3"

In [ ]:
x = 5

if (x == 3) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else {
  x = 2 * x
}

x

[1] 10

In [ ]:
x = 2

if (x == 3) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else {
  x = 2 * x
}

x

[1] 7

In [ ]:
x = 3

if (x == 3) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else {
  x = 2 * x
}

x

[1] 2

In [ ]:
x = 1:10

x

ifelse(x < 6, x^2, x + 1)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  4  9 16 25  7  8  9 10 11

In [ ]:
x = c(7, 9, 8, 4)

ifelse(x %% 2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

In [ ]:
x = c(1, 2, 3, 4, 5, 6)

ifelse(x %% 2 == 0, "even number", "odd number")

[1] "odd number"  "even number" "odd number"  "even number" "odd number"
[6] "even number"

In [ ]:
switch(2, "apple", "banana", "orange")

switch(1, "apple", "banana", "orange")

[1] "banana"

[1] "apple"

In [ ]:
switch("colour",
       "colour" = "blue",
       "gender" = "male",
       "volume" = 50)

switch("volume",
       "colour" = "blue",
       "gender" = "male",
       "volume" = 50)

[1] "blue"

[1] 50

In [ ]:
switch(4, "apple", "banana", "orange")

switch("size",
       "colour" = "blue",
       "gender" = "male",
       "volume" = 50)

In [ ]:
x = c(10, 15, 8, 14, 6, 12)

x

which(x == 14)

which(x != 12)

which(x > 10)

[1] 10 15  8 14  6 12

[1] 4

[1] 1 2 3 4 5

[1] 2 4 6

In [ ]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)

x

which.min(x)

which.max(x)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1

[1] 9

In [ ]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)

x

which(x %% 2 == 1)

which(x %% 2 == 1, arr.ind = TRUE)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1 3 5 7 9

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3