23102A0007 - Aarti Sakpal

In [1]:
x = matrix(nrow=4, ncol=3, data=c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [2]:
rownames(x) = c("r1","r2","r3","r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [3]:
colnames(x) = c("c1","c2","c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [4]:
x = matrix( nrow=4, ncol=2, data=2 )
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [5]:
d = diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [6]:
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [7]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [8]:
xt = t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [9]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [10]:
rowSums(x)

[1]  6  8 10 12

In [11]:
colSums(x)

[1] 10 26

In [12]:
x=matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [13]:
rowMeans(x)

[1] 3 4 5 6

In [14]:
colMeans(x)

[1] 2.5 6.5

In [15]:
x = matrix(nrow=5, ncol=3, byrow=T, data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [16]:
x[3,]

[1] 7 8 9

In [17]:
x[,2]

[1]  2  5  8 11 14

In [18]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [19]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [20]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [21]:
x+5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

In [22]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [23]:
x - 5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

In [24]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [25]:
5*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [26]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [27]:
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

In [28]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)

In [29]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [30]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [31]:
x+y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

In [32]:
x-y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

In [33]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [34]:
4*y

     [,1] [,2]
[1,] 44   48
[2,] 52   56
[3,] 60   64
[4,] 68   72

In [35]:
x + 4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [36]:
4*x - x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

In [37]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)

In [38]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [39]:
y

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

In [40]:
x%*%y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [41]:
y%*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [42]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [43]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [44]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [45]:
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

In [46]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [47]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [48]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [49]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)

In [50]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

In [51]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

In [52]:
rbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

In [53]:
cbind(x, y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

In [54]:
y = matrix(nrow = 2, ncol = 2, byrow = T,
           data = c(84,100,100,120))

In [55]:
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [56]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

In [57]:
y = matrix(nrow = 2, ncol = 2, byrow = T,
           data = c(84,100,100,120))

In [58]:
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [59]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [60]:
x=8
(x < 10) || (x < 2)

[1] TRUE

In [61]:
x=18
(x < 10) || (x < 2)

[1] FALSE

In [65]:
(x < 10) | (x < 2)

[1]  TRUE FALSE

In [66]:
x = 5
(x < 10) && (x > 2)

[1] TRUE

In [67]:
x = 15
(x < 10) && (x > 2)

[1] FALSE

In [69]:
(x < 10) & (x > 2)

[1]  TRUE FALSE

In [70]:
x = 1:6

In [71]:
(x > 2) & (x < 5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [72]:
x[(x > 2) & (x < 5)]

[1] 3 4

In [73]:
x = 1:6

In [74]:
(x > 2) | (x < 5)

[1] TRUE TRUE TRUE TRUE TRUE TRUE

In [75]:
x[(x > 2) | (x < 5)]

[1] 1 2 3 4 5 6

In [76]:
x = 1:6

In [78]:
(x[1] > 2) & (x[1] < 5)

[1] FALSE

In [79]:
x = TRUE
y = FALSE

In [80]:
x & y

[1] FALSE

In [81]:
x | y

[1] TRUE

In [82]:
!x

[1] FALSE

In [83]:
x = 5

In [84]:
Logical1 = (x > 2)
Logical1

[1] TRUE

In [85]:
is.logical(Logical1)

[1] TRUE

In [86]:
Logical2 = (x < 10)
Logical2

[1] TRUE

In [87]:
is.logical(Logical2)

[1] TRUE

In [88]:
Logical3 = (x != 5)
Logical3

[1] FALSE

In [89]:
is.logical(Logical3)

[1] TRUE

In [90]:
x = 5

In [91]:
Logical4 = (2*x > 11)
Logical4

[1] FALSE

In [92]:
is.logical(Logical4)

[1] TRUE

In [93]:
Logical5 = (3*x < 20)
Logical5

[1] TRUE

In [94]:
is.logical(Logical5)

[1] TRUE

In [95]:
8 > 7

[1] TRUE

In [96]:
7 < 5

[1] FALSE

In [97]:
7 > 7

[1] FALSE

In [98]:
7 >= 7

[1] TRUE

In [99]:
8 < 8

[1] FALSE

In [100]:
8 <= 8

[1] TRUE

In [101]:
8 != 9

[1] TRUE

In [102]:
9 != 9

[1] FALSE

In [103]:
7 == 7

[1] TRUE

In [104]:
7 == 8

[1] FALSE

In [105]:
x = TRUE
!x

[1] FALSE

In [106]:
x = c(1, 2, 3)
y = c(4, 5, 6)

In [107]:
x > y

[1] FALSE FALSE FALSE

In [108]:
x < y

[1] TRUE TRUE TRUE

In [109]:
x != y

[1] TRUE TRUE TRUE

In [110]:
x == y

[1] FALSE FALSE FALSE

In [111]:
isTRUE(8 < 6)

[1] FALSE

In [112]:
isTRUE(8 > 6)

[1] TRUE

In [113]:
isFALSE(5 < 8)

[1] FALSE

In [114]:
isFALSE(5 > 8)

[1] TRUE